import type { InsightsModuleProps } from "../types";
import { useHotwordInsights } from "./useHotwordInsights";
import { useInsightDataset } from "./useInsightDataset";
import { useInsightTimeRange } from "./useInsightTimeRange";
import { useInsightComparisonState } from "./useInsightComparisonState";
import { buildInsightMetrics } from "./buildInsightMetrics";
import { buildInsightView } from "./buildInsightView";
import { useInsightSelectionState } from "./useInsightSelectionState";
import { buildInsightEvidenceActions } from "./buildInsightEvidenceActions";
import { buildInsightChartPrelude } from "./buildInsightChartPrelude";
import { buildInsightBusinessChartFactory } from "./buildInsightBusinessCharts";
import { buildInsightStoreSalesChartFactory } from "./buildInsightStoreSalesCharts";
import { buildInsightGovernanceChartFactory } from "./buildInsightGovernanceCharts";
import { useInsightChartSpecs } from "./useInsightChartSpecs";
import { buildInsightChartSelection } from "./buildInsightChartSelection";
import { useInsightContext } from "./useInsightContext";
import { buildInsightReportDraft } from "./buildInsightReportDraft";
import { useInsightReportState } from "./useInsightReportState";
import { buildInsightReportGuards } from "./buildInsightReportGuards";
import { buildInsightReportExecution } from "./buildInsightReportExecution";
import { buildInsightReportActions } from "./buildInsightReportActions";
import { buildInsightAgentAction } from "./buildInsightAgentAction";
import { buildInsightChartRenderer } from "./buildInsightChartRenderer";
import { buildInsightReportRenderer } from "./buildInsightReportRenderer";

export function useInsightsController(props: InsightsModuleProps) {
  const hotwordInsightsState = useHotwordInsights(props);
  const scope1 = Object.assign({ ...props }, hotwordInsightsState);
  const insightDatasetState = useInsightDataset(scope1);
  const scope2 = Object.assign(scope1, insightDatasetState);
  const insightTimeRangeState = useInsightTimeRange(scope2);
  const scope3 = Object.assign(scope2, insightTimeRangeState);
  const insightComparisonState = useInsightComparisonState(scope3);
  const scope4 = Object.assign(scope3, insightComparisonState);
  const insightMetrics = buildInsightMetrics(scope4);
  const scope5 = Object.assign(scope4, insightMetrics);
  const insightView = buildInsightView(scope5);
  const scope6 = Object.assign(scope5, insightView);
  const insightSelectionState = useInsightSelectionState(scope6);
  const scope7 = Object.assign(scope6, insightSelectionState);
  const insightEvidenceActions = buildInsightEvidenceActions(scope7);
  const scope8 = Object.assign(scope7, insightEvidenceActions);
  const insightChartPrelude = buildInsightChartPrelude(scope8);
  const scope9 = Object.assign(scope8, insightChartPrelude);
  const insightBusinessChartFactory = buildInsightBusinessChartFactory(scope9);
  const scope10 = Object.assign(scope9, insightBusinessChartFactory);
  const insightStoreSalesChartFactory = buildInsightStoreSalesChartFactory(scope10);
  const scope11 = Object.assign(scope10, insightStoreSalesChartFactory);
  const insightGovernanceChartFactory = buildInsightGovernanceChartFactory(scope11);
  const scope12 = Object.assign(scope11, insightGovernanceChartFactory);
  const insightChartSpecs = useInsightChartSpecs(scope12);
  const scope13 = Object.assign(scope12, insightChartSpecs);
  const insightChartSelection = buildInsightChartSelection(scope13);
  const scope14 = Object.assign(scope13, insightChartSelection);
  const insightContext = useInsightContext(scope14);
  const scope15 = Object.assign(scope14, insightContext);
  const insightReportDraftBuilder = buildInsightReportDraft(scope15);
  const scope16 = Object.assign(scope15, insightReportDraftBuilder);
  const insightReportState = useInsightReportState(scope16);
  const scope17 = Object.assign(scope16, insightReportState);
  const insightReportGuards = buildInsightReportGuards(scope17);
  const scope18 = Object.assign(scope17, insightReportGuards);
  const insightReportExecution = buildInsightReportExecution(scope18);
  const scope19 = Object.assign(scope18, insightReportExecution);
  const insightReportActions = buildInsightReportActions(scope19);
  const scope20 = Object.assign(scope19, insightReportActions);
  const insightAgentAction = buildInsightAgentAction(scope20);
  const scope21 = Object.assign(scope20, insightAgentAction);
  const insightChartRenderer = buildInsightChartRenderer(scope21);
  const scope22 = Object.assign(scope21, insightChartRenderer);
  const insightReportRenderer = buildInsightReportRenderer(scope22);
  const scope23 = Object.assign(scope22, insightReportRenderer);
  return scope23;
}

export type InsightsController = ReturnType<typeof useInsightsController>;
