import type { CanvasModuleProps } from "../types";
import { useCanvasState } from "./useCanvasState";
import { buildCanvasPrimitiveActions } from "./buildCanvasPrimitiveActions";
import { useCanvasRecovery } from "./useCanvasRecovery";
import { buildCanvasSectionModel } from "./buildCanvasSectionModel";
import { useCanvasScheduleModel } from "./useCanvasScheduleModel";
import { buildCanvasExecutionPlan } from "./buildCanvasExecutionPlan";
import { useCanvasRuntimeModel } from "./useCanvasRuntimeModel";
import { buildCanvasNodeCollections } from "./buildCanvasNodeCollections";
import { buildCanvasNodeContextModel } from "./buildCanvasNodeContextModel";
import { buildCanvasNodeInteractions } from "./buildCanvasNodeInteractions";
import { buildCanvasTaskDagModel } from "./buildCanvasTaskDagModel";
import { buildCanvasConfiguredNodeActions } from "./buildCanvasConfiguredNodeActions";
import { buildCanvasDraftModelActions } from "./buildCanvasDraftModelActions";
import { buildCanvasReleaseActions } from "./buildCanvasReleaseActions";
import { buildCanvasExecutionActions } from "./buildCanvasExecutionActions";
import { buildCanvasExperimentStateActions } from "./buildCanvasExperimentStateActions";
import { buildCanvasExperimentCreateActions } from "./buildCanvasExperimentCreateActions";
import { buildCanvasExperimentActions } from "./buildCanvasExperimentActions";
import { buildCanvasRunModel } from "./buildCanvasRunModel";
import { buildCanvasToolbarModel } from "./buildCanvasToolbarModel";

export function useCanvasController(props: CanvasModuleProps) {
  const state = useCanvasState(props);
  const scope1 = Object.assign({ ...props }, state);
  const primitiveActions = buildCanvasPrimitiveActions(scope1);
  const scope2 = Object.assign(scope1, primitiveActions);
  const recoveryModel = useCanvasRecovery(scope2);
  const scope3 = Object.assign(scope2, recoveryModel);
  const sectionModel = buildCanvasSectionModel(scope3);
  const scope4 = Object.assign(scope3, sectionModel);
  const scheduleModel = useCanvasScheduleModel(scope4);
  const scope5 = Object.assign(scope4, scheduleModel);
  const executionPlan = buildCanvasExecutionPlan(scope5);
  const scope6 = Object.assign(scope5, executionPlan);
  const runtimeModel = useCanvasRuntimeModel(scope6);
  const scope7 = Object.assign(scope6, runtimeModel);
  const nodeCollections = buildCanvasNodeCollections(scope7);
  const scope8 = Object.assign(scope7, nodeCollections);
  const nodeContextModel = buildCanvasNodeContextModel(scope8);
  const scope9 = Object.assign(scope8, nodeContextModel);
  const nodeInteractions = buildCanvasNodeInteractions(scope9);
  const scope10 = Object.assign(scope9, nodeInteractions);
  const taskDagModel = buildCanvasTaskDagModel(scope10);
  const scope11 = Object.assign(scope10, taskDagModel);
  const configuredNodeActions = buildCanvasConfiguredNodeActions(scope11);
  const scope12 = Object.assign(scope11, configuredNodeActions);
  const draftModelActions = buildCanvasDraftModelActions(scope12);
  const scope13 = Object.assign(scope12, draftModelActions);
  const releaseActions = buildCanvasReleaseActions(scope13);
  const scope14 = Object.assign(scope13, releaseActions);
  const executionActions = buildCanvasExecutionActions(scope14);
  const scope15 = Object.assign(scope14, executionActions);
  const experimentStateActions = buildCanvasExperimentStateActions(scope15);
  const scope16 = Object.assign(scope15, experimentStateActions);
  const experimentCreateActions = buildCanvasExperimentCreateActions(scope16);
  const scope17 = Object.assign(scope16, experimentCreateActions);
  const experimentActions = buildCanvasExperimentActions(scope17);
  const scope18 = Object.assign(scope17, experimentActions);
  const runModel = buildCanvasRunModel(scope18);
  const scope19 = Object.assign(scope18, runModel);
  const toolbarModel = buildCanvasToolbarModel(scope19);
  const scope20 = Object.assign(scope19, toolbarModel);
  return scope20;
}

export type CanvasController = ReturnType<typeof useCanvasController>;
